deploy_staging:
  type: deploy
  variables:
      ID_RSA_NAME: $CI_PROJECT_PATH_SLUG"_dev"
  environment:
    name: staging
    url: jennytexo.knovator.in
  before_script:
    - mkdir -p ~/.ssh
    - echo -e "$STAGE_SSH_KEY" > ~/.ssh/$ID_RSA_NAME
    - chmod 600 ~/.ssh/$ID_RSA_NAME
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - ssh -i "~/.ssh/$ID_RSA_NAME" "$STAGE_USER_NAME"@"$STAGE_SERVER_HOST" "cd $STAGE_PATH && git checkout development && git pull origin development && composer install && php artisan migrate && php artisan module:optimize && php artisan store:routes && php artisan queue:restart && exit"
  only:
    - development


deploy_production:
  type: deploy
  variables:
      ID_RSA_NAME: $CI_PROJECT_PATH_SLUG"_prod"
  environment:
    name: production
    url: jennytexo.knovator.in
  before_script:
      - mkdir -p ~/.ssh
      - echo -e "$PROD_SSH_KEY" > ~/.ssh/$ID_RSA_NAME
      - chmod 600 ~/.ssh/$ID_RSA_NAME
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - ssh -i "~/.ssh/$ID_RSA_NAME" "$PROD_USER_NAME"@"$PROD_SERVER_HOST" "cd $PROD_PATH && git checkout master && git pull origin master && composer install && composer dump-autoload && php artisan migrate && php artisan module:optimize && php artisan queue:restart && exit"
  only:
    - master
